Convert to Optimistic Goerli
truffle-box/optimism-box pull request #26
Opened 2022-07-17 03:13 UTC by emilyJLin95

Modified scripts and README
Deleted node_modules, as that should not be committed

2022-07-17 20:28 UTC, kevinbluer approved these changes
Looks good from a quick review on my 📱

2022-07-18 05:07 UTC, fainashalts requested changes
LGTM, with a couple tiny changes. Thanks for doing this!

2022-07-18 05:07 UTC, fainashalts commented on README.md
> +  * Currently, we have the gasPrice for transactions on Optimistic Goerli set to zero. You should be able to use this network as configured at this time.
This is no longer true, as far as I know. Can you remove this bullet?

2022-07-18 05:07 UTC, fainashalts commented on README.md
> +The information above should allow you to deploy to the Optimism Layer 2 chain. This is only the first step! Once you are ready to deploy your own contracts to function on Layer 1 using Layer 2, you
```suggestion
The information above should allow you to deploy to the Optimism Layer 2 chain. This is only the first step! Once you are ready to deploy your own contracts to function on Layer 1 using Layer 2, you will need to be aware of the [ways in which Layer 1 and Layer 2 interact in the Optimism ecosystem](http://community.optimism.io/docs/developers/integration.html#bridging-l1-and-l2). We have an [Optimism Bridge Box](https://trufflesuite.com/blog/introducing-the-optimism-bridge-truffle-box/?utm_source=github&utm_medium=devcommunity&utm_campaign=2022_Jul_optimism-box-readme_tutorial_content) that shows you just how to do that!
```

2022-07-18 15:41 UTC, merged